In [ ]:
#Import the numpy package under the name np

import numpy as np

In [ ]:
#Print the numpy version and the configuration 

print(np.__version__)
print(np.show_config())

1.18.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [ ]:
#Create a null vector of size 10

a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#How to find the memory size of any array

a = np.ones((5,5))
print(a.size * a.itemsize)

#in this method we have multiplied size of 'a' which is 25 with itemsize which is 8, 25*8.

#we can also use
from sys import getsizeof
getsizeof(a)
a.nbytes

#in the second method we have imported one library from sys as getsizeof which is mainly used for finding the size of particular array

200


200

In [ ]:
#Create a null vector of size 10 but the fifth value which is 1

b = np.zeros(10)
print(b)

print("updating the 5th value to 1")
b[5] = 1
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
updating the 5th value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
# Create a vector with values ranging from 10 to 49

b = np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#Reverse a vector (first element becomes last)

b = np.arange(10,49)
print("oringinal Vector",b ,"\n")

print("Reversing the vector:")
b[::-1]

oringinal Vector [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48] 

Reversing the vector:


array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8 

b = np.arange(0,8)
n = b.reshap

ValueError: ignored

In [ ]:
#Create a 3x3 identity matrix

b = np.identity(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Create a 3x3x3 array with random values

b = np.random.random((3,3,3))
print(b)

[[[0.78524261 0.23476903 0.530392  ]
  [0.53134201 0.0507431  0.88944089]
  [0.93142849 0.97067699 0.94429953]]

 [[0.63287623 0.32893277 0.05139575]
  [0.33733384 0.41203162 0.64531517]
  [0.27748276 0.33679624 0.74497056]]

 [[0.47279825 0.53312467 0.83856293]
  [0.23218916 0.3871268  0.60150455]
  [0.38875949 0.53983296 0.31910593]]]


In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values

b = np.random.random((10,10))
print(b, "\n")

print("Minimum Value is:", b.min(), "\n")

print("Maximum Value is:", b.max())

[[0.01009824 0.84441579 0.33006811 0.63682493 0.34487869 0.86065828
  0.24108371 0.7042152  0.21256972 0.61399732]
 [0.82579082 0.82720301 0.09041795 0.80209704 0.38358457 0.18306348
  0.57941771 0.78272777 0.89777069 0.8423796 ]
 [0.34334784 0.39148523 0.04606123 0.36748253 0.83173639 0.7700576
  0.80373695 0.7005736  0.02929934 0.45573841]
 [0.70541132 0.88416348 0.8346658  0.61698768 0.95975028 0.99200432
  0.98765562 0.47762113 0.56854463 0.91353873]
 [0.70997391 0.65799122 0.41038182 0.68272445 0.35497938 0.91040832
  0.6770795  0.12975113 0.71478544 0.27125381]
 [0.97507334 0.18936451 0.35784097 0.67627204 0.09340722 0.16235517
  0.39570852 0.25439054 0.10641188 0.20625147]
 [0.09286995 0.39857181 0.29963118 0.61000998 0.29162201 0.86516317
  0.81859246 0.87357477 0.68460784 0.69011863]
 [0.77028252 0.25020071 0.52064703 0.57848938 0.08376003 0.68451287
  0.99017448 0.46428504 0.10529539 0.15114648]
 [0.96121119 0.35933656 0.34160564 0.24449528 0.95536347 0.91958571
  0.63150952 

In [ ]:
#Create a random vector of size 30 and find the mean value

a = np.random.random(30)
print("original array", a, "\n")

print("The Mean Value is :",a.mean())

original array [0.60498093 0.01178016 0.17074768 0.10380434 0.72042586 0.87187857
 0.70128567 0.79377153 0.43939553 0.33845743 0.68492591 0.85663664
 0.94245709 0.87814293 0.40699625 0.46185695 0.5313962  0.19994441
 0.7704329  0.83825803 0.97951379 0.32950928 0.16730017 0.94022318
 0.59751683 0.60081349 0.92377252 0.04185909 0.68775043 0.60105731] 

The Mean Value is : 0.5732297040875962


In [ ]:
#Create a 2d array with 1 on the border and 0 inside

a = np.ones((5,5))
print("Original Array is :")
print(a,"\n")

a[1:-1,1:-1] = 0
print("array with 1 on the bordr and 0 inside")
print(a)

Original Array is :
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

array with 1 on the bordr and 0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#How to add a border (filled with 0’s) around an existing array? 
a = np.ones((5,5))
print(a, "\n")

print("0 on the border and 1 inside in the array")
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
#Normalize a 5x5 random matrix

a = np.random.random((5,5))
print("Original Matrix")
print(a, "\n")

amax , amin = a.max(), a.min()
a = (a - amin) / (amax - amin)
print("Matrix After Normalization")
print(a)

Original Matrix
[[0.08389021 0.60859045 0.20641512 0.68669743 0.3489012 ]
 [0.63497057 0.45442193 0.14341745 0.88149612 0.94887271]
 [0.07257181 0.56039209 0.21402343 0.45003377 0.2255522 ]
 [0.579816   0.75886926 0.32901833 0.58820119 0.50668245]
 [0.24833104 0.90629863 0.70351234 0.16705149 0.69654965]] 

Matrix After Normalization
[[0.01291612 0.61168332 0.1527367  0.70081592 0.31533619]
 [0.64178726 0.43575229 0.08084625 0.9231125  1.        ]
 [0.         0.55668125 0.16141901 0.43074469 0.17457519]
 [0.57884706 0.78317556 0.29264665 0.5884159  0.49538993]
 [0.20056951 0.95141614 0.72000443 0.10781648 0.71205889]]


In [ ]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

a = np.random.random((5,3))
print("first Matrix")
print(a, "\n")

b = np.random.random((3,2))
print("Second Matrix")
print(b, "\n")

c = np.dot(a,b)
print("Multiplication of two matrix is")
print(c)

first Matrix
[[0.0082422  0.37842177 0.29861672]
 [0.66762055 0.16430597 0.90146713]
 [0.10408296 0.84772489 0.57997566]
 [0.07958201 0.81481753 0.7338168 ]
 [0.12558237 0.08349075 0.74503648]] 

Second Matrix
[[0.40254131 0.72982393]
 [0.76653559 0.51286368]
 [0.66273041 0.0667443 ]] 

Multiplication of two matrix is
[[0.49129396 0.2200251 ]
 [0.9921209  0.6316798 ]
 [1.0760765  0.54943962]
 [1.1429444  0.52494926]
 [0.60830906 0.18419934]]


In [ ]:
#Given a 1D array, negate all elements which are between 3 and 8, in place

a = np.arange(0,10)
a = np.delete(a,3,8)
a

AxisError: ignored

In [ ]:
#What is the output of the following script?

print(sum(range(5),-1)) 
from numpy import * 
print(sum(range(5),-1)) 

9
10


In [ ]:
#How to find common values between two arrays?

ab1 = np.array([0,1,2,3,4,5,6])
print("First Array {}".format(ab1))
ab2 = np.array([0,3,4,5,11,12,34])
print("Second Array {}".format(ab2), "\n")

print("Comman Values Between two Arrays are")
print(np.intersect1d(ab1,ab2))


First Array [0 1 2 3 4 5 6]
Second Array [ 0  3  4  5 11 12 34] 

Comman Values Between two Arrays are
[0 3 4 5]


In [ ]:
#Is the following expressions true? 

np.sqrt(-1) == np.emath.sqrt(-1)

#its False because the value we entered for the Square it is inavlid, its an negative value
#reference link = https://math.stackexchange.com/questions/677619/why-is-the-square-root-of-a-negative-number-impossible#:~:text=Any%20number%20times%20itself%20is,can't%20have%20square%20roots.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [ ]:
#Create a 5x5 matrix with row values ranging from 0 to 4
ab = np.zeros((5,5))
ab += np.arange(5)
print("Values Ranging from 0 to 4")
print(ab)

Values Ranging from 0 to 4
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded

ab = np.linspace(0,1,12,endpoint=True)[1:-1]
print(ab)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#Create a random vector of size 10 and sort it 

ab1 = np.random.random(10)
print("Original Array")
print(ab1, "\n")

print("Sorted Array")
ab1.sort()
print(ab1)

Original Array
[0.70574201 0.71434786 0.50928116 0.41639062 0.75785838 0.30565133
 0.80049521 0.5725733  0.89953832 0.33652862] 

Sorted Array
[0.30565133 0.33652862 0.41639062 0.50928116 0.5725733  0.70574201
 0.71434786 0.75785838 0.80049521 0.89953832]


In [ ]:
#Consider two random array A and B, check if they are equal 
#a = list(input("Enter"))

A = np.random.randint(1,2,3)
print("First Array")
print(A, "\n")

#b = list(input("Enter"))

B = np.random.randint(1,2,3)
print("Second Array")
print(B, "\n")

print("Check if two arrays are equal or not")
ar_equal = np.allclose(A, B)

#Returns True if two arrays are element-wise equal within a tolerance.
#The tolerance values are positive, typically very small numbers. 
#The relative difference (rtol * abs(b)) and the absolute difference atol are added together to compare against the absolute difference between a and b.
#NaNs are treated as equal if they are in the same place and if equal_nan=True. 
#Infs are treated as equal if they are in the same place and of the same sign in both arrays.

print(ar_equal)

First Array
[1 1 1] 

Second Array
[1 1 1] 

Check if two arrays are equal or not
True
